version: "3.8"
services:
  golang_ecs_mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: golang_ecs
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

volumes:
  mongo: